server:
  port: 8080

app:
  uploads-dir: C:/Users/Abid Khan/Downloads/FlexiFaaS Project/uploads

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

info:
  app:
    name: FlexiFaaS Backend API
    description: Serverless Function Deployment Engine - REST APIs
    version: 1.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flexifaas_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Imak@143
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # or use 'create' for first run to create schema, then switch to 'update'
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
# Optional: File upload directory
file:
  upload-dir: ./uploads

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
